// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	utils "github.com/guncv/tech-exam-software-engineering/utils"
)

// MockIPasetoMaker is an autogenerated mock type for the IPasetoMaker type
type MockIPasetoMaker struct {
	mock.Mock
}

type MockIPasetoMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPasetoMaker) EXPECT() *MockIPasetoMaker_Expecter {
	return &MockIPasetoMaker_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: userId, duration
func (_m *MockIPasetoMaker) CreateToken(userId string, duration time.Duration) (string, error) {
	ret := _m.Called(userId, duration)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(userId, duration)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(userId, duration)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(userId, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPasetoMaker_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockIPasetoMaker_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - userId string
//   - duration time.Duration
func (_e *MockIPasetoMaker_Expecter) CreateToken(userId interface{}, duration interface{}) *MockIPasetoMaker_CreateToken_Call {
	return &MockIPasetoMaker_CreateToken_Call{Call: _e.mock.On("CreateToken", userId, duration)}
}

func (_c *MockIPasetoMaker_CreateToken_Call) Run(run func(userId string, duration time.Duration)) *MockIPasetoMaker_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockIPasetoMaker_CreateToken_Call) Return(_a0 string, _a1 error) *MockIPasetoMaker_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPasetoMaker_CreateToken_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *MockIPasetoMaker_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: token
func (_m *MockIPasetoMaker) VerifyToken(token string) (*utils.Payload, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *utils.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*utils.Payload, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *utils.Payload); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPasetoMaker_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockIPasetoMaker_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - token string
func (_e *MockIPasetoMaker_Expecter) VerifyToken(token interface{}) *MockIPasetoMaker_VerifyToken_Call {
	return &MockIPasetoMaker_VerifyToken_Call{Call: _e.mock.On("VerifyToken", token)}
}

func (_c *MockIPasetoMaker_VerifyToken_Call) Run(run func(token string)) *MockIPasetoMaker_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIPasetoMaker_VerifyToken_Call) Return(_a0 *utils.Payload, _a1 error) *MockIPasetoMaker_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPasetoMaker_VerifyToken_Call) RunAndReturn(run func(string) (*utils.Payload, error)) *MockIPasetoMaker_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPasetoMaker creates a new instance of MockIPasetoMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPasetoMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPasetoMaker {
	mock := &MockIPasetoMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
