// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/guncv/tech-exam-software-engineering/infras/log"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/guncv/tech-exam-software-engineering/utils"
)

// MockIPayload is an autogenerated mock type for the IPayload type
type MockIPayload struct {
	mock.Mock
}

type MockIPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPayload) EXPECT() *MockIPayload_Expecter {
	return &MockIPayload_Expecter{mock: &_m.Mock}
}

// GetAuthPayload provides a mock function with given fields: ctx, _a1
func (_m *MockIPayload) GetAuthPayload(ctx context.Context, _a1 *log.Logger) (*utils.Payload, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthPayload")
	}

	var r0 *utils.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *log.Logger) (*utils.Payload, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *log.Logger) *utils.Payload); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *log.Logger) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPayload_GetAuthPayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthPayload'
type MockIPayload_GetAuthPayload_Call struct {
	*mock.Call
}

// GetAuthPayload is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *log.Logger
func (_e *MockIPayload_Expecter) GetAuthPayload(ctx interface{}, _a1 interface{}) *MockIPayload_GetAuthPayload_Call {
	return &MockIPayload_GetAuthPayload_Call{Call: _e.mock.On("GetAuthPayload", ctx, _a1)}
}

func (_c *MockIPayload_GetAuthPayload_Call) Run(run func(ctx context.Context, _a1 *log.Logger)) *MockIPayload_GetAuthPayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*log.Logger))
	})
	return _c
}

func (_c *MockIPayload_GetAuthPayload_Call) Return(_a0 *utils.Payload, _a1 error) *MockIPayload_GetAuthPayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPayload_GetAuthPayload_Call) RunAndReturn(run func(context.Context, *log.Logger) (*utils.Payload, error)) *MockIPayload_GetAuthPayload_Call {
	_c.Call.Return(run)
	return _c
}

// Valid provides a mock function with no fields
func (_m *MockIPayload) Valid() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPayload_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockIPayload_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
func (_e *MockIPayload_Expecter) Valid() *MockIPayload_Valid_Call {
	return &MockIPayload_Valid_Call{Call: _e.mock.On("Valid")}
}

func (_c *MockIPayload_Valid_Call) Run(run func()) *MockIPayload_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPayload_Valid_Call) Return(_a0 error) *MockIPayload_Valid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPayload_Valid_Call) RunAndReturn(run func() error) *MockIPayload_Valid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPayload creates a new instance of MockIPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPayload {
	mock := &MockIPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
