// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/guncv/tech-exam-software-engineering/entities"
	mock "github.com/stretchr/testify/mock"

	models "github.com/guncv/tech-exam-software-engineering/models"
)

// MockITaskRepository is an autogenerated mock type for the ITaskRepository type
type MockITaskRepository struct {
	mock.Mock
}

type MockITaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITaskRepository) EXPECT() *MockITaskRepository_Expecter {
	return &MockITaskRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockITaskRepository) CreateTask(ctx context.Context, task *models.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockITaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *models.Task
func (_e *MockITaskRepository_Expecter) CreateTask(ctx interface{}, task interface{}) *MockITaskRepository_CreateTask_Call {
	return &MockITaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockITaskRepository_CreateTask_Call) Run(run func(ctx context.Context, task *models.Task)) *MockITaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Task))
	})
	return _c
}

func (_c *MockITaskRepository_CreateTask_Call) Return(_a0 error) *MockITaskRepository_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITaskRepository_CreateTask_Call) RunAndReturn(run func(context.Context, *models.Task) error) *MockITaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: ctx, id
func (_m *MockITaskRepository) DeleteTask(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockITaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockITaskRepository_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockITaskRepository_DeleteTask_Call {
	return &MockITaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockITaskRepository_DeleteTask_Call) Run(run func(ctx context.Context, id string)) *MockITaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITaskRepository_DeleteTask_Call) Return(_a0 error) *MockITaskRepository_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITaskRepository_DeleteTask_Call) RunAndReturn(run func(context.Context, string) error) *MockITaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTasks provides a mock function with given fields: ctx, req, userId
func (_m *MockITaskRepository) GetAllTasks(ctx context.Context, req *entities.GetAllTasksRequest, userId string) (*[]models.Task, error) {
	ret := _m.Called(ctx, req, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 *[]models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetAllTasksRequest, string) (*[]models.Task, error)); ok {
		return rf(ctx, req, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.GetAllTasksRequest, string) *[]models.Task); ok {
		r0 = rf(ctx, req, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.GetAllTasksRequest, string) error); ok {
		r1 = rf(ctx, req, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITaskRepository_GetAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTasks'
type MockITaskRepository_GetAllTasks_Call struct {
	*mock.Call
}

// GetAllTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - req *entities.GetAllTasksRequest
//   - userId string
func (_e *MockITaskRepository_Expecter) GetAllTasks(ctx interface{}, req interface{}, userId interface{}) *MockITaskRepository_GetAllTasks_Call {
	return &MockITaskRepository_GetAllTasks_Call{Call: _e.mock.On("GetAllTasks", ctx, req, userId)}
}

func (_c *MockITaskRepository_GetAllTasks_Call) Run(run func(ctx context.Context, req *entities.GetAllTasksRequest, userId string)) *MockITaskRepository_GetAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.GetAllTasksRequest), args[2].(string))
	})
	return _c
}

func (_c *MockITaskRepository_GetAllTasks_Call) Return(_a0 *[]models.Task, _a1 error) *MockITaskRepository_GetAllTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITaskRepository_GetAllTasks_Call) RunAndReturn(run func(context.Context, *entities.GetAllTasksRequest, string) (*[]models.Task, error)) *MockITaskRepository_GetAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, id
func (_m *MockITaskRepository) GetTask(ctx context.Context, id string) (*models.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITaskRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockITaskRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockITaskRepository_Expecter) GetTask(ctx interface{}, id interface{}) *MockITaskRepository_GetTask_Call {
	return &MockITaskRepository_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockITaskRepository_GetTask_Call) Run(run func(ctx context.Context, id string)) *MockITaskRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITaskRepository_GetTask_Call) Return(_a0 *models.Task, _a1 error) *MockITaskRepository_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITaskRepository_GetTask_Call) RunAndReturn(run func(context.Context, string) (*models.Task, error)) *MockITaskRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockITaskRepository) HealthCheck(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITaskRepository_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockITaskRepository_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockITaskRepository_Expecter) HealthCheck(ctx interface{}) *MockITaskRepository_HealthCheck_Call {
	return &MockITaskRepository_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockITaskRepository_HealthCheck_Call) Run(run func(ctx context.Context)) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockITaskRepository_HealthCheck_Call) Return(_a0 string, _a1 error) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITaskRepository_HealthCheck_Call) RunAndReturn(run func(context.Context) (string, error)) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, task
func (_m *MockITaskRepository) UpdateTask(ctx context.Context, task *models.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockITaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *models.Task
func (_e *MockITaskRepository_Expecter) UpdateTask(ctx interface{}, task interface{}) *MockITaskRepository_UpdateTask_Call {
	return &MockITaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, task)}
}

func (_c *MockITaskRepository_UpdateTask_Call) Run(run func(ctx context.Context, task *models.Task)) *MockITaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Task))
	})
	return _c
}

func (_c *MockITaskRepository_UpdateTask_Call) Return(_a0 error) *MockITaskRepository_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITaskRepository_UpdateTask_Call) RunAndReturn(run func(context.Context, *models.Task) error) *MockITaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITaskRepository creates a new instance of MockITaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITaskRepository {
	mock := &MockITaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
