// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockITaskRepository is an autogenerated mock type for the ITaskRepository type
type MockITaskRepository struct {
	mock.Mock
}

type MockITaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITaskRepository) EXPECT() *MockITaskRepository_Expecter {
	return &MockITaskRepository_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockITaskRepository) HealthCheck(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITaskRepository_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockITaskRepository_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockITaskRepository_Expecter) HealthCheck(ctx interface{}) *MockITaskRepository_HealthCheck_Call {
	return &MockITaskRepository_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockITaskRepository_HealthCheck_Call) Run(run func(ctx context.Context)) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockITaskRepository_HealthCheck_Call) Return(_a0 string, _a1 error) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITaskRepository_HealthCheck_Call) RunAndReturn(run func(context.Context) (string, error)) *MockITaskRepository_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITaskRepository creates a new instance of MockITaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITaskRepository {
	mock := &MockITaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
