AppConfig:
  APP_PORT: 8080
  APP_ENV: local

Database:
  POSTGRES_HOST: task-db
  POSTGRES_PORT: 5432
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: task-note

TokenConfig:
  TOKEN_SYMMETRIC_KEY: 12345678901234567890123456789012
  ACCESS_TOKEN_DURATION: 15m
